// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: microgrid/iot/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the iot module's genesis state.
type GenesisState struct {
	Params     Params   `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	GridList   []Grid   `protobuf:"bytes,2,rep,name=gridList,proto3" json:"gridList"`
	GridCount  uint64   `protobuf:"varint,3,opt,name=gridCount,proto3" json:"gridCount,omitempty"`
	DeviceList []Device `protobuf:"bytes,4,rep,name=deviceList,proto3" json:"deviceList"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd19de6366df9680, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetGridList() []Grid {
	if m != nil {
		return m.GridList
	}
	return nil
}

func (m *GenesisState) GetGridCount() uint64 {
	if m != nil {
		return m.GridCount
	}
	return 0
}

func (m *GenesisState) GetDeviceList() []Device {
	if m != nil {
		return m.DeviceList
	}
	return nil
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "microgrid.iot.GenesisState")
}

func init() { proto.RegisterFile("microgrid/iot/genesis.proto", fileDescriptor_dd19de6366df9680) }

var fileDescriptor_dd19de6366df9680 = []byte{
	// 287 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x31, 0x4b, 0xc3, 0x40,
	0x18, 0x86, 0x73, 0xb6, 0x14, 0xbd, 0xea, 0x12, 0x15, 0x42, 0x94, 0x33, 0x38, 0x65, 0x4a, 0xb0,
	0xc5, 0xc9, 0xad, 0x0a, 0x1d, 0x74, 0x90, 0xba, 0xb9, 0x5d, 0x92, 0x23, 0x7e, 0x68, 0x72, 0xe1,
	0xf2, 0x45, 0xf4, 0x5f, 0xf8, 0xb3, 0x3a, 0x76, 0x11, 0x9c, 0x44, 0x92, 0x3f, 0x22, 0xb9, 0x0b,
	0xad, 0x0d, 0x6e, 0xc7, 0xbd, 0xcf, 0xf7, 0xf0, 0xf2, 0xd2, 0x93, 0x0c, 0x62, 0x25, 0x53, 0x05,
	0x49, 0x08, 0x12, 0xc3, 0x54, 0xe4, 0xa2, 0x84, 0x32, 0x28, 0x94, 0x44, 0x69, 0x1f, 0xac, 0xc3,
	0x00, 0x24, 0xba, 0x47, 0xa9, 0x4c, 0xa5, 0x4e, 0xc2, 0xf6, 0x65, 0x20, 0xd7, 0xdd, 0x36, 0x14,
	0x5c, 0xf1, 0xac, 0x13, 0xb8, 0x4e, 0xcf, 0xde, 0x9a, 0xfe, 0xbd, 0x4a, 0xc4, 0x2b, 0xc4, 0xc2,
	0x64, 0xe7, 0x9f, 0x84, 0xee, 0xcf, 0x4d, 0x91, 0x07, 0xe4, 0x28, 0xec, 0x29, 0x1d, 0x19, 0xad,
	0x43, 0x3c, 0xe2, 0x8f, 0x27, 0xc7, 0xc1, 0x56, 0xb1, 0xe0, 0x5e, 0x87, 0xb3, 0xe1, 0xf2, 0xfb,
	0xcc, 0x5a, 0x74, 0xa8, 0x7d, 0x49, 0x77, 0x5b, 0xe0, 0x0e, 0x4a, 0x74, 0x76, 0xbc, 0x81, 0x3f,
	0x9e, 0x1c, 0xf6, 0xce, 0xe6, 0x0a, 0x92, 0xee, 0x68, 0x8d, 0xda, 0xa7, 0x74, 0xaf, 0x7d, 0x5f,
	0xcb, 0x2a, 0x47, 0x67, 0xe0, 0x11, 0x7f, 0xb8, 0xd8, 0x7c, 0xd8, 0x57, 0x94, 0x9a, 0xaa, 0x5a,
	0x3b, 0xd4, 0xda, 0x7e, 0x9b, 0x1b, 0x0d, 0x74, 0xe2, 0x3f, 0xf8, 0xec, 0x76, 0x59, 0x33, 0xb2,
	0xaa, 0x19, 0xf9, 0xa9, 0x19, 0xf9, 0x68, 0x98, 0xb5, 0x6a, 0x98, 0xf5, 0xd5, 0x30, 0xeb, 0xf1,
	0x22, 0x05, 0x7c, 0xaa, 0xa2, 0x20, 0x96, 0x59, 0x88, 0x90, 0x73, 0xfe, 0x02, 0xfc, 0x39, 0xe2,
	0xaa, 0x90, 0x95, 0x0a, 0x37, 0x4b, 0xbd, 0xe9, 0xad, 0xf0, 0xbd, 0x10, 0x65, 0x34, 0xd2, 0x5b,
	0x4d, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x6d, 0xb8, 0x3e, 0x49, 0xc1, 0x01, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DeviceList) > 0 {
		for iNdEx := len(m.DeviceList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DeviceList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if m.GridCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.GridCount))
		i--
		dAtA[i] = 0x18
	}
	if len(m.GridList) > 0 {
		for iNdEx := len(m.GridList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.GridList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.GridList) > 0 {
		for _, e := range m.GridList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.GridCount != 0 {
		n += 1 + sovGenesis(uint64(m.GridCount))
	}
	if len(m.DeviceList) > 0 {
		for _, e := range m.DeviceList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GridList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GridList = append(m.GridList, Grid{})
			if err := m.GridList[len(m.GridList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GridCount", wireType)
			}
			m.GridCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GridCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeviceList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DeviceList = append(m.DeviceList, Device{})
			if err := m.DeviceList[len(m.DeviceList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
