// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: microgrid/iot/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f292a0696b0c1eb1, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f292a0696b0c1eb1, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetGridRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetGridRequest) Reset()         { *m = QueryGetGridRequest{} }
func (m *QueryGetGridRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetGridRequest) ProtoMessage()    {}
func (*QueryGetGridRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f292a0696b0c1eb1, []int{2}
}
func (m *QueryGetGridRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetGridRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetGridRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetGridRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetGridRequest.Merge(m, src)
}
func (m *QueryGetGridRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetGridRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetGridRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetGridRequest proto.InternalMessageInfo

func (m *QueryGetGridRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryGetGridResponse struct {
	Grid Grid `protobuf:"bytes,1,opt,name=Grid,proto3" json:"Grid"`
}

func (m *QueryGetGridResponse) Reset()         { *m = QueryGetGridResponse{} }
func (m *QueryGetGridResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetGridResponse) ProtoMessage()    {}
func (*QueryGetGridResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f292a0696b0c1eb1, []int{3}
}
func (m *QueryGetGridResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetGridResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetGridResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetGridResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetGridResponse.Merge(m, src)
}
func (m *QueryGetGridResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetGridResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetGridResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetGridResponse proto.InternalMessageInfo

func (m *QueryGetGridResponse) GetGrid() Grid {
	if m != nil {
		return m.Grid
	}
	return Grid{}
}

type QueryAllGridRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllGridRequest) Reset()         { *m = QueryAllGridRequest{} }
func (m *QueryAllGridRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllGridRequest) ProtoMessage()    {}
func (*QueryAllGridRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f292a0696b0c1eb1, []int{4}
}
func (m *QueryAllGridRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllGridRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllGridRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllGridRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllGridRequest.Merge(m, src)
}
func (m *QueryAllGridRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllGridRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllGridRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllGridRequest proto.InternalMessageInfo

func (m *QueryAllGridRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllGridResponse struct {
	Grid       []Grid              `protobuf:"bytes,1,rep,name=Grid,proto3" json:"Grid"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllGridResponse) Reset()         { *m = QueryAllGridResponse{} }
func (m *QueryAllGridResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllGridResponse) ProtoMessage()    {}
func (*QueryAllGridResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f292a0696b0c1eb1, []int{5}
}
func (m *QueryAllGridResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllGridResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllGridResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllGridResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllGridResponse.Merge(m, src)
}
func (m *QueryAllGridResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllGridResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllGridResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllGridResponse proto.InternalMessageInfo

func (m *QueryAllGridResponse) GetGrid() []Grid {
	if m != nil {
		return m.Grid
	}
	return nil
}

func (m *QueryAllGridResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetDeviceRequest struct {
	GridId  uint64 `protobuf:"varint,1,opt,name=gridId,proto3" json:"gridId,omitempty"`
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *QueryGetDeviceRequest) Reset()         { *m = QueryGetDeviceRequest{} }
func (m *QueryGetDeviceRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetDeviceRequest) ProtoMessage()    {}
func (*QueryGetDeviceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f292a0696b0c1eb1, []int{6}
}
func (m *QueryGetDeviceRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetDeviceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetDeviceRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetDeviceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetDeviceRequest.Merge(m, src)
}
func (m *QueryGetDeviceRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetDeviceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetDeviceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetDeviceRequest proto.InternalMessageInfo

func (m *QueryGetDeviceRequest) GetGridId() uint64 {
	if m != nil {
		return m.GridId
	}
	return 0
}

func (m *QueryGetDeviceRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type QueryGetDeviceResponse struct {
	Device Device `protobuf:"bytes,1,opt,name=device,proto3" json:"device"`
}

func (m *QueryGetDeviceResponse) Reset()         { *m = QueryGetDeviceResponse{} }
func (m *QueryGetDeviceResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetDeviceResponse) ProtoMessage()    {}
func (*QueryGetDeviceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f292a0696b0c1eb1, []int{7}
}
func (m *QueryGetDeviceResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetDeviceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetDeviceResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetDeviceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetDeviceResponse.Merge(m, src)
}
func (m *QueryGetDeviceResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetDeviceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetDeviceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetDeviceResponse proto.InternalMessageInfo

func (m *QueryGetDeviceResponse) GetDevice() Device {
	if m != nil {
		return m.Device
	}
	return Device{}
}

type QueryAllDeviceRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllDeviceRequest) Reset()         { *m = QueryAllDeviceRequest{} }
func (m *QueryAllDeviceRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllDeviceRequest) ProtoMessage()    {}
func (*QueryAllDeviceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f292a0696b0c1eb1, []int{8}
}
func (m *QueryAllDeviceRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllDeviceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllDeviceRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllDeviceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllDeviceRequest.Merge(m, src)
}
func (m *QueryAllDeviceRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllDeviceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllDeviceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllDeviceRequest proto.InternalMessageInfo

func (m *QueryAllDeviceRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllDeviceResponse struct {
	Device     []Device            `protobuf:"bytes,1,rep,name=device,proto3" json:"device"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllDeviceResponse) Reset()         { *m = QueryAllDeviceResponse{} }
func (m *QueryAllDeviceResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllDeviceResponse) ProtoMessage()    {}
func (*QueryAllDeviceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f292a0696b0c1eb1, []int{9}
}
func (m *QueryAllDeviceResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllDeviceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllDeviceResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllDeviceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllDeviceResponse.Merge(m, src)
}
func (m *QueryAllDeviceResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllDeviceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllDeviceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllDeviceResponse proto.InternalMessageInfo

func (m *QueryAllDeviceResponse) GetDevice() []Device {
	if m != nil {
		return m.Device
	}
	return nil
}

func (m *QueryAllDeviceResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryListDeviceByGridIdRequest struct {
	GridId uint64 `protobuf:"varint,1,opt,name=gridId,proto3" json:"gridId,omitempty"`
}

func (m *QueryListDeviceByGridIdRequest) Reset()         { *m = QueryListDeviceByGridIdRequest{} }
func (m *QueryListDeviceByGridIdRequest) String() string { return proto.CompactTextString(m) }
func (*QueryListDeviceByGridIdRequest) ProtoMessage()    {}
func (*QueryListDeviceByGridIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f292a0696b0c1eb1, []int{10}
}
func (m *QueryListDeviceByGridIdRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryListDeviceByGridIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryListDeviceByGridIdRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryListDeviceByGridIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListDeviceByGridIdRequest.Merge(m, src)
}
func (m *QueryListDeviceByGridIdRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryListDeviceByGridIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListDeviceByGridIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListDeviceByGridIdRequest proto.InternalMessageInfo

func (m *QueryListDeviceByGridIdRequest) GetGridId() uint64 {
	if m != nil {
		return m.GridId
	}
	return 0
}

type QueryListDeviceByGridIdResponse struct {
	Device []*Device `protobuf:"bytes,1,rep,name=device,proto3" json:"device,omitempty"`
}

func (m *QueryListDeviceByGridIdResponse) Reset()         { *m = QueryListDeviceByGridIdResponse{} }
func (m *QueryListDeviceByGridIdResponse) String() string { return proto.CompactTextString(m) }
func (*QueryListDeviceByGridIdResponse) ProtoMessage()    {}
func (*QueryListDeviceByGridIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f292a0696b0c1eb1, []int{11}
}
func (m *QueryListDeviceByGridIdResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryListDeviceByGridIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryListDeviceByGridIdResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryListDeviceByGridIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListDeviceByGridIdResponse.Merge(m, src)
}
func (m *QueryListDeviceByGridIdResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryListDeviceByGridIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListDeviceByGridIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListDeviceByGridIdResponse proto.InternalMessageInfo

func (m *QueryListDeviceByGridIdResponse) GetDevice() []*Device {
	if m != nil {
		return m.Device
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "microgrid.iot.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "microgrid.iot.QueryParamsResponse")
	proto.RegisterType((*QueryGetGridRequest)(nil), "microgrid.iot.QueryGetGridRequest")
	proto.RegisterType((*QueryGetGridResponse)(nil), "microgrid.iot.QueryGetGridResponse")
	proto.RegisterType((*QueryAllGridRequest)(nil), "microgrid.iot.QueryAllGridRequest")
	proto.RegisterType((*QueryAllGridResponse)(nil), "microgrid.iot.QueryAllGridResponse")
	proto.RegisterType((*QueryGetDeviceRequest)(nil), "microgrid.iot.QueryGetDeviceRequest")
	proto.RegisterType((*QueryGetDeviceResponse)(nil), "microgrid.iot.QueryGetDeviceResponse")
	proto.RegisterType((*QueryAllDeviceRequest)(nil), "microgrid.iot.QueryAllDeviceRequest")
	proto.RegisterType((*QueryAllDeviceResponse)(nil), "microgrid.iot.QueryAllDeviceResponse")
	proto.RegisterType((*QueryListDeviceByGridIdRequest)(nil), "microgrid.iot.QueryListDeviceByGridIdRequest")
	proto.RegisterType((*QueryListDeviceByGridIdResponse)(nil), "microgrid.iot.QueryListDeviceByGridIdResponse")
}

func init() { proto.RegisterFile("microgrid/iot/query.proto", fileDescriptor_f292a0696b0c1eb1) }

var fileDescriptor_f292a0696b0c1eb1 = []byte{
	// 709 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x95, 0x4d, 0x6b, 0x13, 0x4f,
	0x1c, 0xc7, 0xb3, 0x69, 0xff, 0x29, 0x9d, 0x3f, 0x7a, 0x98, 0x3e, 0x50, 0x17, 0xd9, 0xea, 0xd8,
	0xd6, 0xfa, 0xd0, 0x1d, 0xd2, 0x5e, 0x14, 0x0f, 0x92, 0xa2, 0x86, 0xfa, 0x00, 0x35, 0x47, 0x41,
	0xc2, 0x24, 0x3b, 0xac, 0x83, 0x9b, 0xcc, 0x76, 0x67, 0x52, 0x0c, 0xa5, 0x28, 0x3d, 0x79, 0x12,
	0x41, 0x10, 0x5f, 0x8c, 0x2f, 0xa0, 0xc7, 0x82, 0x17, 0x4f, 0x22, 0xad, 0x6f, 0xc1, 0xbb, 0xec,
	0xcc, 0x6c, 0xdb, 0x4d, 0x36, 0xd9, 0x3d, 0xf4, 0x96, 0xd9, 0xf9, 0xce, 0xef, 0xfb, 0x99, 0xdf,
	0xc3, 0x04, 0x5c, 0xe9, 0xb0, 0x76, 0xc4, 0xfd, 0x88, 0x79, 0x98, 0x71, 0x89, 0x77, 0x7a, 0x34,
	0xea, 0xbb, 0x61, 0xc4, 0x25, 0x87, 0x97, 0x4e, 0xb7, 0x5c, 0xc6, 0xa5, 0x3d, 0xeb, 0x73, 0x9f,
	0xab, 0x1d, 0x1c, 0xff, 0xd2, 0x22, 0xfb, 0xaa, 0xcf, 0xb9, 0x1f, 0x50, 0x4c, 0x42, 0x86, 0x49,
	0xb7, 0xcb, 0x25, 0x91, 0x8c, 0x77, 0x85, 0xd9, 0xbd, 0xdd, 0xe6, 0xa2, 0xc3, 0x05, 0x6e, 0x11,
	0x41, 0x75, 0x6c, 0xbc, 0x5b, 0x6d, 0x51, 0x49, 0xaa, 0x38, 0x24, 0x3e, 0xeb, 0x2a, 0xb1, 0xd1,
	0xda, 0x69, 0x92, 0x90, 0x44, 0xa4, 0x93, 0xc4, 0x59, 0x48, 0xef, 0x29, 0xa6, 0xcc, 0x53, 0x1e,
	0xdd, 0x65, 0x6d, 0xaa, 0xf7, 0xd0, 0x2c, 0x80, 0x2f, 0x63, 0xcf, 0x6d, 0x15, 0xaa, 0x41, 0x77,
	0x7a, 0x54, 0x48, 0xf4, 0x14, 0xcc, 0xa4, 0xbe, 0x8a, 0x90, 0x77, 0x05, 0x85, 0x1b, 0xa0, 0xa2,
	0x2d, 0x17, 0xac, 0x6b, 0xd6, 0xea, 0xff, 0xeb, 0x73, 0x6e, 0xea, 0xfa, 0xae, 0x96, 0x6f, 0x4e,
	0x1e, 0xfe, 0x5a, 0x2c, 0x35, 0x8c, 0x14, 0x2d, 0x9b, 0x58, 0x75, 0x2a, 0xeb, 0x11, 0xf3, 0x8c,
	0x05, 0xbc, 0x0c, 0xca, 0xcc, 0x53, 0x71, 0x26, 0x1b, 0x65, 0xe6, 0xa1, 0xc7, 0x60, 0x36, 0x2d,
	0x33, 0x9e, 0x6b, 0x60, 0x32, 0x5e, 0x1b, 0xc7, 0x99, 0x01, 0xc7, 0x78, 0xcb, 0xf8, 0x29, 0x19,
	0x7a, 0x6d, 0xdc, 0x6a, 0x41, 0x70, 0xde, 0xed, 0x09, 0x00, 0x67, 0xc9, 0x34, 0xb1, 0x56, 0x5c,
	0x9d, 0x79, 0x37, 0xce, 0xbc, 0xab, 0xab, 0x6a, 0x32, 0xef, 0x6e, 0x13, 0x9f, 0x9a, 0xb3, 0x8d,
	0x73, 0x27, 0xd1, 0x27, 0xcb, 0x60, 0x9e, 0xc6, 0x1f, 0xc2, 0x9c, 0x28, 0x80, 0x09, 0xeb, 0x29,
	0x9e, 0xb2, 0xe2, 0xb9, 0x99, 0xcb, 0xa3, 0xbd, 0x52, 0x40, 0x5b, 0x60, 0x2e, 0x49, 0xdb, 0x23,
	0x55, 0xd7, 0xe4, 0xc6, 0xf3, 0xa0, 0x12, 0xdb, 0x6f, 0x25, 0x39, 0x36, 0x2b, 0xb8, 0x00, 0xa6,
	0x88, 0xe7, 0x45, 0x54, 0x08, 0x65, 0x3b, 0xdd, 0x48, 0x96, 0xe8, 0x05, 0x98, 0x1f, 0x0c, 0x75,
	0x56, 0x77, 0xdd, 0x34, 0x23, 0xea, 0xae, 0xe5, 0x49, 0xdd, 0xb5, 0x14, 0x35, 0x0d, 0x59, 0x2d,
	0x08, 0xd2, 0x64, 0x17, 0x55, 0x8b, 0xaf, 0x96, 0x01, 0x3e, 0xe7, 0x90, 0x01, 0x3c, 0x51, 0x10,
	0xf8, 0xe2, 0x6a, 0x72, 0x0f, 0x38, 0x8a, 0xeb, 0x39, 0x13, 0x26, 0x93, 0x9b, 0xfd, 0xba, 0xca,
	0x7e, 0x4e, 0x71, 0xd0, 0x36, 0x58, 0x1c, 0x79, 0xf2, 0xb4, 0xd1, 0x8a, 0x5c, 0x2d, 0xb9, 0xd4,
	0xfa, 0xdf, 0x0a, 0xf8, 0x4f, 0x85, 0x84, 0xef, 0x41, 0x45, 0xcf, 0x27, 0xbc, 0x3e, 0x70, 0x64,
	0xf8, 0x01, 0xb0, 0xd1, 0x38, 0x89, 0x26, 0x41, 0xee, 0xc1, 0x8f, 0x3f, 0x5f, 0xca, 0xab, 0x70,
	0x05, 0x4b, 0xd6, 0x25, 0x24, 0x60, 0xe4, 0x6d, 0x8b, 0x44, 0x21, 0xef, 0x45, 0x38, 0xeb, 0x99,
	0x82, 0x07, 0x96, 0x9e, 0x11, 0x98, 0x19, 0x3c, 0xfd, 0x3c, 0xd8, 0x37, 0xc6, 0x6a, 0x0c, 0x41,
	0x55, 0x11, 0xdc, 0x81, 0xb7, 0xf2, 0x08, 0xd4, 0x8f, 0x3d, 0xe6, 0xed, 0xc3, 0x0f, 0x16, 0x98,
	0x8a, 0x63, 0xd4, 0x82, 0x20, 0x9b, 0x23, 0xfd, 0x70, 0x64, 0x73, 0x0c, 0x0c, 0x3f, 0xba, 0xab,
	0x38, 0x56, 0xe0, 0x52, 0x11, 0x0e, 0xf8, 0xcd, 0x02, 0x15, 0x5d, 0x25, 0xb8, 0x34, 0xe2, 0x96,
	0xa9, 0x81, 0xb1, 0x97, 0x73, 0x54, 0x86, 0xa2, 0xa6, 0x28, 0x1e, 0xc0, 0xfb, 0x79, 0x14, 0xba,
	0x35, 0xf0, 0x9e, 0x6e, 0xba, 0x7d, 0xbc, 0x67, 0x5e, 0x80, 0x7d, 0xf8, 0xd1, 0x02, 0xd3, 0x3a,
	0x6a, 0x9c, 0x9f, 0xa5, 0x11, 0x77, 0x2f, 0x40, 0x37, 0x34, 0x92, 0xc5, 0xbb, 0xc5, 0x4c, 0xe3,
	0x77, 0x0b, 0xc0, 0xe1, 0x31, 0x80, 0x6b, 0x59, 0x6e, 0x23, 0x07, 0xcd, 0x76, 0x8b, 0xca, 0x0d,
	0x65, 0x5d, 0x51, 0xd6, 0xe0, 0xc3, 0x3c, 0xca, 0x80, 0x09, 0xd9, 0xd4, 0xa8, 0xcd, 0x56, 0xbf,
	0x19, 0x7f, 0x6f, 0xc6, 0x3d, 0x66, 0x72, 0xba, 0xf9, 0xec, 0xf0, 0xd8, 0xb1, 0x8e, 0x8e, 0x1d,
	0xeb, 0xf7, 0xb1, 0x63, 0x7d, 0x3e, 0x71, 0x4a, 0x47, 0x27, 0x4e, 0xe9, 0xe7, 0x89, 0x53, 0x7a,
	0x55, 0xf5, 0x99, 0x7c, 0xd3, 0x6b, 0xb9, 0x6d, 0xde, 0x19, 0x67, 0xf2, 0x4e, 0xd9, 0xc8, 0x7e,
	0x48, 0x45, 0xab, 0xa2, 0xfe, 0xab, 0x37, 0xfe, 0x05, 0x00, 0x00, 0xff, 0xff, 0x0b, 0xd0, 0xdb,
	0x17, 0x89, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of Grid items.
	Grid(ctx context.Context, in *QueryGetGridRequest, opts ...grpc.CallOption) (*QueryGetGridResponse, error)
	GridAll(ctx context.Context, in *QueryAllGridRequest, opts ...grpc.CallOption) (*QueryAllGridResponse, error)
	// // Queries a list of Device items.
	Device(ctx context.Context, in *QueryGetDeviceRequest, opts ...grpc.CallOption) (*QueryGetDeviceResponse, error)
	DeviceAll(ctx context.Context, in *QueryAllDeviceRequest, opts ...grpc.CallOption) (*QueryAllDeviceResponse, error)
	// Queries a list of ListDeviceByGridId items.
	ListDeviceByGridId(ctx context.Context, in *QueryListDeviceByGridIdRequest, opts ...grpc.CallOption) (*QueryListDeviceByGridIdResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/microgrid.iot.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Grid(ctx context.Context, in *QueryGetGridRequest, opts ...grpc.CallOption) (*QueryGetGridResponse, error) {
	out := new(QueryGetGridResponse)
	err := c.cc.Invoke(ctx, "/microgrid.iot.Query/Grid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GridAll(ctx context.Context, in *QueryAllGridRequest, opts ...grpc.CallOption) (*QueryAllGridResponse, error) {
	out := new(QueryAllGridResponse)
	err := c.cc.Invoke(ctx, "/microgrid.iot.Query/GridAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Device(ctx context.Context, in *QueryGetDeviceRequest, opts ...grpc.CallOption) (*QueryGetDeviceResponse, error) {
	out := new(QueryGetDeviceResponse)
	err := c.cc.Invoke(ctx, "/microgrid.iot.Query/Device", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) DeviceAll(ctx context.Context, in *QueryAllDeviceRequest, opts ...grpc.CallOption) (*QueryAllDeviceResponse, error) {
	out := new(QueryAllDeviceResponse)
	err := c.cc.Invoke(ctx, "/microgrid.iot.Query/DeviceAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListDeviceByGridId(ctx context.Context, in *QueryListDeviceByGridIdRequest, opts ...grpc.CallOption) (*QueryListDeviceByGridIdResponse, error) {
	out := new(QueryListDeviceByGridIdResponse)
	err := c.cc.Invoke(ctx, "/microgrid.iot.Query/ListDeviceByGridId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of Grid items.
	Grid(context.Context, *QueryGetGridRequest) (*QueryGetGridResponse, error)
	GridAll(context.Context, *QueryAllGridRequest) (*QueryAllGridResponse, error)
	// // Queries a list of Device items.
	Device(context.Context, *QueryGetDeviceRequest) (*QueryGetDeviceResponse, error)
	DeviceAll(context.Context, *QueryAllDeviceRequest) (*QueryAllDeviceResponse, error)
	// Queries a list of ListDeviceByGridId items.
	ListDeviceByGridId(context.Context, *QueryListDeviceByGridIdRequest) (*QueryListDeviceByGridIdResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) Grid(ctx context.Context, req *QueryGetGridRequest) (*QueryGetGridResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Grid not implemented")
}
func (*UnimplementedQueryServer) GridAll(ctx context.Context, req *QueryAllGridRequest) (*QueryAllGridResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GridAll not implemented")
}
func (*UnimplementedQueryServer) Device(ctx context.Context, req *QueryGetDeviceRequest) (*QueryGetDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Device not implemented")
}
func (*UnimplementedQueryServer) DeviceAll(ctx context.Context, req *QueryAllDeviceRequest) (*QueryAllDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeviceAll not implemented")
}
func (*UnimplementedQueryServer) ListDeviceByGridId(ctx context.Context, req *QueryListDeviceByGridIdRequest) (*QueryListDeviceByGridIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDeviceByGridId not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/microgrid.iot.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Grid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetGridRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Grid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/microgrid.iot.Query/Grid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Grid(ctx, req.(*QueryGetGridRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GridAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllGridRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GridAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/microgrid.iot.Query/GridAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GridAll(ctx, req.(*QueryAllGridRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Device_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Device(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/microgrid.iot.Query/Device",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Device(ctx, req.(*QueryGetDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_DeviceAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).DeviceAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/microgrid.iot.Query/DeviceAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).DeviceAll(ctx, req.(*QueryAllDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListDeviceByGridId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryListDeviceByGridIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListDeviceByGridId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/microgrid.iot.Query/ListDeviceByGridId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListDeviceByGridId(ctx, req.(*QueryListDeviceByGridIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "microgrid.iot.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "Grid",
			Handler:    _Query_Grid_Handler,
		},
		{
			MethodName: "GridAll",
			Handler:    _Query_GridAll_Handler,
		},
		{
			MethodName: "Device",
			Handler:    _Query_Device_Handler,
		},
		{
			MethodName: "DeviceAll",
			Handler:    _Query_DeviceAll_Handler,
		},
		{
			MethodName: "ListDeviceByGridId",
			Handler:    _Query_ListDeviceByGridId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "microgrid/iot/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetGridRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetGridRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetGridRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetGridResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetGridResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetGridResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Grid.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllGridRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllGridRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllGridRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllGridResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllGridResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllGridResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Grid) > 0 {
		for iNdEx := len(m.Grid) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Grid[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetDeviceRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetDeviceRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetDeviceRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x12
	}
	if m.GridId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.GridId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetDeviceResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetDeviceResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetDeviceResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Device.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllDeviceRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllDeviceRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllDeviceRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllDeviceResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllDeviceResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllDeviceResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Device) > 0 {
		for iNdEx := len(m.Device) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Device[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryListDeviceByGridIdRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryListDeviceByGridIdRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryListDeviceByGridIdRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.GridId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.GridId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryListDeviceByGridIdResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryListDeviceByGridIdResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryListDeviceByGridIdResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Device) > 0 {
		for iNdEx := len(m.Device) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Device[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetGridRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryGetGridResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Grid.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllGridRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllGridResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Grid) > 0 {
		for _, e := range m.Grid {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetDeviceRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.GridId != 0 {
		n += 1 + sovQuery(uint64(m.GridId))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetDeviceResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Device.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllDeviceRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllDeviceResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Device) > 0 {
		for _, e := range m.Device {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryListDeviceByGridIdRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.GridId != 0 {
		n += 1 + sovQuery(uint64(m.GridId))
	}
	return n
}

func (m *QueryListDeviceByGridIdResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Device) > 0 {
		for _, e := range m.Device {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetGridRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetGridRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetGridRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetGridResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetGridResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetGridResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Grid", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Grid.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllGridRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllGridRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllGridRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllGridResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllGridResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllGridResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Grid", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Grid = append(m.Grid, Grid{})
			if err := m.Grid[len(m.Grid)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetDeviceRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetDeviceRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetDeviceRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GridId", wireType)
			}
			m.GridId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GridId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetDeviceResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetDeviceResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetDeviceResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Device", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Device.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllDeviceRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllDeviceRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllDeviceRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllDeviceResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllDeviceResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllDeviceResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Device", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Device = append(m.Device, Device{})
			if err := m.Device[len(m.Device)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryListDeviceByGridIdRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryListDeviceByGridIdRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryListDeviceByGridIdRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GridId", wireType)
			}
			m.GridId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GridId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryListDeviceByGridIdResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryListDeviceByGridIdResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryListDeviceByGridIdResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Device", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Device = append(m.Device, &Device{})
			if err := m.Device[len(m.Device)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
